### ISSUE TITLE
Basic cup should be centered

### ISSUE THREAD

**Issue by RussNelson** [vector76/gridfinity_openscad#1]
If you create a basic cup with any values other than 1,1 only the first grid unit is centered. The whole module should be centered.

**Comment by RussNelson** [comment]
I suggest this because the largest glue stick you can hold without overlapping the edges is 34mm. Bigger than that, and it needs to use a 2x2 storage unit to hold the stick.

**Comment by vector76** [comment]
I've updated grid block to have an option to center the assembly in X/Y (but not Z), somewhat analogous to the option in the native OpenSCAD cube().  7a81cb26ac3db598b1b274acb1f8680bb33545fa
