### ISSUE TITLE
Feature Request: centered labeling shelves

### ISSUE THREAD

**Issue by mrmattmorris** [vector76/gridfinity_openscad#21]
The labeling shelves serve two purposes: 1) holding labels;  and 2) acting as a finger catch to lift bins up when they're surrounded by adjacent bins.  As currently implemented, label shelves are always 'left- or right-justified'.  This makes it a bit awkward to lift wide bins that use short label shelves  -- where the lift is happening away from the center of mass.

It could be useful to offer a option to center the label shelves for users who would prefer 'center justification'.  

I've already implemented these changes to gridfinity_cup_modules.scad.  I can make a pull request if the owner is interested.

![2022-10-13_111429](https://user-images.githubusercontent.com/23463715/195650289-35ab0ac3-d86a-465d-a39d-a3f22415bfd5.jpg)

**Comment by mrmattmorris** [comment]
Whoops, this is already underway as [PR#20](https://github.com/vector76/gridfinity_openscad/pull/20).  Consider this a vote in support.

**Comment by vector76** [comment]
Thank you. This has been implemented by #20 but I haven't had a chance to review and merge it. I am guessing will probably be accepting that PR but if you have some commentary, since you have been considering the same issue, I would be interested to hear it.

**Comment by vector76** [comment]
Thanks, I will close this issue as essentially duplicate.
