### ISSUE TITLE
Unable to use z-height lower than 2

### ISSUE THREAD

**Issue by MrUzagi** [vector76/gridfinity_openscad#24]
This is using the files downloaded from GitHub Dec 13th where the latest modifications dates are Dec 1st (on my computer at GMT +1.)

Setting the height of less than two (actually less than 1.26 after some investigation) the base of the cup is missing the middle bits. 

A 1x1 cup with z at 2:
![image](https://user-images.githubusercontent.com/21023158/209702217-cfed5d16-354a-4dac-8d9a-50ef972053b3.png)

A 1x1 cup with z at 1:
![image](https://user-images.githubusercontent.com/21023158/209702174-f5376197-9e71-4749-8872-ed5dbacf0044.png)

Editing the height in the script we can check smaller steps.
1.20
![image](https://user-images.githubusercontent.com/21023158/209703531-e641732e-aeb5-4520-a668-34e4076055ff.png)

1.25
![image](https://user-images.githubusercontent.com/21023158/209703559-9d6e0a28-ff10-4f3c-9b46-38beb2658008.png)

At 1.26 it looks closed
![image](https://user-images.githubusercontent.com/21023158/209703663-a24bdaa8-2e99-42e1-8c84-118f4037c102.png)

**Comment by MrUzagi** [comment]
I've only recently started to familiarize myself with OpenSCAD so I haven't been able to track down the reason for this as of yet.

**Comment by vector76** [comment]
Indeed, some of the cutaways for cutting downward from the lip and upward from the bottom were interfering with each other.

I just pushed an update and these are now reduced, and also now it automatically forces 'reduced' or 'none' lip style for very low Z.

Some of the internal fillets are not great, and the finger slide is still broken for low Z, but it should fix the issues you were having.

**Comment by MrUzagi** [comment]
Looking good now. Thanks, and happy new year. 🎆
