### ISSUE TITLE
why import?

### ISSUE THREAD

**Issue by RussNelson** [vector76/gridfinity_openscad#3]
Why are Zack's baseplates being imported into gridfinity_baseplate.scad? Is that just for comparison's sake?
Also, the simple baseplate's holes are not fully cut out. I had to make this change. Is this correct?
-    render() gridcopy(num_x, num_y) pad_oversize(margins=1);
+    translate([0,0,-0.01]) render() gridcopy(num_x, num_y) pad_oversize(margins=1);

**Comment by vector76** [comment]
oops!  I meant to remove those imports.  I use those during construction to confirm the dimensions match exactly.

The plain frame has a negative space that coincides with the bottom of the positive space, which doesn't render properly in preview mode (appears not fully cut out) but when rendered it is fully cut out.  Shifting downward by 0.01 will fix the preview at the expense of a very small deviation from Zack's models.  Overall, I think it is close enough and the preview appearance does matter, so I'm willing to include your update for that.

**Comment by vector76** [comment]
addressed by 1be92633c44ab8c1248270a54d34d8ec4def1df2
